name: deploy-book

on:
  push:
    branches:
    - main
  schedule:
    - cron: '14 1/4 * * *'
    
    
# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TYPE: ${{ secrets.TYPE }}
      PID: ${{ secrets.PID }}
      PKID: ${{ secrets.PKID }}
      PK: ${{ secrets.PK }}
      CE: ${{ secrets.CE }}
      CID: ${{ secrets.CID }}
      AURI: ${{ secrets.AURI }}
      TURI: ${{ secrets.TURI }}
      AUTHP: ${{ secrets.AUTHP }}
      CLIURL: ${{ secrets.CLIURL }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v4 #@v2

    - name: Set up Python 
      uses: actions/setup-python@v5 #@v2
      with:
        python-version: '3.10' #3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set the git credentials
      run: |
             git config --global user.name "GithubActionRunner"
             git config --global user.email "githubactionrunner"
   
    - name: Retrieve new data from ThingSpeak # run the run.py to get the latest data
      run: |
           python3 ThingSpeakAPI.py
    
    - name: commit changes
      run: |
            git add -A
            ls -la
    - name: push changes
      run: |
           git commit -m "updating thingspeak data $(date +"%D %T")"
           git push
              
    - name: Build the book
      run: |
        jupyter-book clean .
        jupyter-book build . --builder html
    
    - name: Upload HTML artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "_build/html"
    
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


 
    # - name: Move Processed data to public folder
    #   run: |
    #     mv data ./_build/html/
    # # Push the book's HTML to github-pages
    # - name: GitHub Pages action
    #   uses: peaceiris/actions-gh-pages@v3.6.1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./_build/html

# stuff about fetching standalone data from Google Drive -
# never used but we should reinstate a simpler version for Thermopros.
   # Download 'data' folder from Google Drive
#   - name: Make Python Directory #Download from Google Drive
#   run: |
#        mkdir -p data
#         python3 downloadDrive.py
         
# # mv -f input data/input
# # mv -f output data/output
# # mv -f processed data/processed

#     # Process the data for duplicates etc
#     - name: Process Data
#       run: |
#         python3 process_data.py data

#     - name: Upload Processed Files
#     # Upload processed files
#       run: |
#         python3 uploadDrive.py data
